name: ci

on:
  push:
    branches:
      - main
  schedule:
    - cron: "55 13 * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set up Git configuration
        run: |
          git config --local user.email "1497055242@qq.com"
          git config --local user.name "Qi_YiJun"

      - name: Make changes
        run: |
          echo "Changes made at $(date)" >> changes.txt
          git add changes.txt

      - name: Commit and push changes
        run: |
          git commit -m "update changes.txt"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}